// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include "MainRuntime_parameters.h"


// Affine/affine/W
float MainRuntime_parameter1[] = {
       0.827002227306366,
     -0.5443034768104553,
     0.15941771864891052,
    0.023407330736517906,
     0.30305376648902893,
    -0.15215584635734558,
      1.4096426963806152,
     0.07144025713205338,
       0.828619122505188,
     0.36279767751693726,
};

// Affine/affine/b
float MainRuntime_parameter2[] = {
    -0.34896421432495117,
    -0.42531293630599976,
    -0.49956178665161133,
      0.6832552552223206,
    -0.08367954939603806,
};

// Affine_2/affine/W
float MainRuntime_parameter3[] = {
    0.012860117480158806,
      0.4670449495315552,
     0.27075543999671936,
    -0.20613837242126465,
    -0.08913100510835648,
};

// Affine_2/affine/b
float MainRuntime_parameter4[] = {
     -1.1500965356826782,
};

void* MainRuntime_parameters[] ={
    (void*)MainRuntime_parameter1,
    (void*)MainRuntime_parameter2,
    (void*)MainRuntime_parameter3,
    (void*)MainRuntime_parameter4,
};
